### ISSUE TITLE
making engine serializable

### ISSUE THREAD

**Issue by cyliu0204** [zhztheplayer/DFA-Regex#10]

**Comment by cyliu0204** [comment]
while we want to use it in Spark, it seems not support serialization,any idea to support it ?

**Comment by zhztheplayer** [comment]
Hi @cyliu0204, cloud you please share a bit more about the scenario in which the serialization is supposed to take place? E.g. to serialize a compiled RegEx then broadcast to other network locations, etc.

**Comment by cyliu0204** [comment]
Spark operations like(map, flatMap, filter, foreachPartition, mapPartition etc..), if inner part has reference to outer part object, that object needs to be serialized. Because outer part objects are in Driver, not in Executors.  As we need to specify the filter logic using the regex in the flatMap operation,  we need the 'regex component ' be serializable to help us improve the regex proformance

**Comment by cyliu0204** [comment]
As I have tried a pattern like [a-zA-Z], it seems like not support the feature which combine muliti pattern inside the brackets?

**Comment by zhztheplayer** [comment]
> Spark operations like(map, flatMap, filter, foreachPartition, mapPartition etc..), if inner part has reference to outer part object, that object needs to be serialized. Because outer part objects are in Driver, not in Executors. As we need to specify the filter logic using the regex in the flatMap operation, we need the 'regex component ' be serializable to help us improve the regex proformance

I didn't remember this but does that mean Spark requires objects to extend interface `java.io.Serializable`? It should be a straightforward change to current code such as `RegexMatcher` and `RegexSearcher`.

> As I have tried a pattern like [a-zA-Z]...

This is because we don't support operator `-` in this library yet. You can use multiple characters inside the brackets but `-` is not recognizable for now. I doubt that you can use this library as a replacement of traditional POSIX RegEx libraries because of the limitation of supported syntax and character sets. I recommend you to run some tests against the real cases you are facing to see how many types of features are missing from this library, then maybe we can cooperate to come up with a solution accordingly.

**Comment by zhztheplayer** [comment]
Closing. Feel free to reopen if needed.
