### ISSUE TITLE
Pattern problems

### ISSUE THREAD

**Issue by almondtools** [zhztheplayer/DFA-Regex#4]
I have tested your engine with diverse patterns, in order to benchmark them:

- searching `(ab|a|bcdef|g)+` in `xxxabcdefg` should return `abcdefg` but does not
- searching in long texts (or with long texts) throws `IndexOutOfBoundsException`

You do not mention the alternation operator. This would be an explanation.

You may find the (failing 3) Unit-Tests at https://github.com/almondtools/regexbench/blob/master/src/test/java/com/almondtools/regexbench/incubation/DFArgxBenchmarkTest.java

**Comment by zhztheplayer** [comment]
@almondtools 
> - searching (ab|a|bcdef|g)+ in xxxabcdefg should return abcdefg but does not

This is because the current DFA-Regex is based on shortest matching if incoming pattern includes '*' or '+', I am considering adding an option to switch between shortest and longest matching, but still not have time to do that.

> - searching in long texts (or with long texts) throws IndexOutOfBoundsException

I tried ths Test and found a '\ufffd' char in the 
 [sample file](https://github.com/almondtools/regexbench/blob/master/src/main/resources/samples/test9.sample), which is beyond the character bound of DFA-Regex (for now support ascii only, not for unicode), and I am planing to add a bond check for avoiding this confusing.

Thanks for your post Almondtools, And any contribution about above things will be welcomed.
